### ISSUE TITLE
wireless charger (wificharge) requires minecraft 1.12.1

### ISSUE THREAD

**Issue by flapili** [CreeperShift/WirelessCharger#3]
![sans titre](https://user-images.githubusercontent.com/29481952/30771368-a1cef128-a046-11e7-84d8-3db788df21d3.png)

for all version of wirelesscharger (1.0.0 to 1.2.0)
forge 14.21.1.2443

**Comment by CreeperShift** [comment]
Fixed in 1.3.0, should be on curse in a few minutes.
