### ISSUE TITLE
What does the personal charger do?

### ISSUE THREAD

**Issue by PapiDimmi** [CreeperShift/WirelessCharger#7]
I assume it only charges the items of the player who placed it?

**Comment by CreeperShift** [comment]
Exactly.

**Comment by CreeperShift** [comment]
It doesn't have the range restriction of the regular charger

**Comment by PapiDimmi** [comment]
What does that mean? So, it will just charge items no matter where you are in the world? :thinking:

**Comment by PapiDimmi** [comment]
What does that mean? So, it will charge items no matter where you are in the world? :thinking:

**Comment by CreeperShift** [comment]
Exactly even through worlds if the config is set. Make sure it's chunk
loaded

**Comment by PapiDimmi** [comment]
That seems a bit OP, lol.

**Comment by CreeperShift** [comment]
Right maybe look at how much rf it costs per range and dimension instead of
making a very unhelpful comment.

**Comment by PapiDimmi** [comment]
I know my comment was dumb, which is why I deleted it a minute after posting it.

**Comment by CreeperShift** [comment]
Didn't see lol. Replying via email :P

**Comment by PapiDimmi** [comment]
¯\\\_(ツ)_/¯
